apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-config
  namespace: aaw-backend
data:
  AUTH_HOST: authentication.aaw-backend.svc.cluster.local:8000
  DB_HOST: tenant-db.aaw-backend.svc.cluster.local
  DB_PORT: "5432"
  NODE_ENV: production
  PORT: "8004"
  TENANT_ID: e4f770bf-9181-4d75-8ebe-8a9e4db5055c
  vector.yaml: |
    sources:
      logfile:
        type: file
        include:
          - ./logs/*.log

    transforms:
      parse_json:
        type: remap
        inputs:
          - logfile
        source: |
          del(.file)
          del(.source_type)
          . = parse_json!(.message)
          .time = now()
          
    sinks:
      loki:
        type: loki
        inputs:
          - parse_json
        compression: snappy
        endpoint: http://loki.logging.svc.cluster.local:3100
        labels:
          container: app-tenant
          stream: stream-tenant
          level: "{{ .level }}"
          hostname: "{{ .hostname }}"
          pid: "{{ .pid }}"
        encoding:
          codec: json