apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant
  namespace: aaw-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
      - name: tenant
        image: rayhanrandi10/aaw-tenant:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
        envFrom:
        - configMapRef:
            name: tenant-config
        - secretRef:
            name: tenant-secrets
        volumeMounts:
        - name: tenant-storage
          mountPath: /app/data
      volumes:
      - name: tenant-storage
        persistentVolumeClaim:
          claimName: tenant-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: tenant
  namespace: aaw-backend
spec:
  type: NodePort
  selector:
    app: tenant
  ports:
  - protocol: TCP
    nodePort:  30004
    port: 8004
    targetPort: 8004
