apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant
  namespace: aaw-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
      - name: tenant
        image: rayhanrandi10/aaw-tenant:capstone
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
        envFrom:
        - configMapRef:
            name: tenant-config
        - secretRef:
            name: tenant-secrets
        volumeMounts:
        - name: tenant-storage
          mountPath: /app/data
        - name: vector-log-volume
          mountPath: /logs

      - name: vector-agent
        image: timberio/vector:0.42.0-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8686
        envFrom:
        - configMapRef:
            name: authentication-config
        volumeMounts:
        - name: vector-log-volume
          mountPath: /logs
        - name: vector-config-volume
          mountPath: /etc/vector
        args: 
            - "-c"
            - "/etc/vector/vector.yaml"
 
      volumes:
      - name: tenant-storage
        persistentVolumeClaim:
          claimName: tenant-pvc
      - name: vector-log-volume
        emptyDir: {}
      - name: vector-config-volume
        configMap:
          name: tenant-config

---
apiVersion: v1
kind: Service
metadata:
  name: tenant
  namespace: aaw-backend
spec:
  type: NodePort
  selector:
    app: tenant
  ports:
  - name: http
    protocol: TCP
    nodePort:  30004
    port: 8004
    targetPort: 8004
