apiVersion: v1
kind: Secret
metadata:
  name: authentication-secrets
  namespace: aaw-backend
type: Opaque
data:
  JWT_SECRET: "YXV0aF9tc19qd3Rfc2VjcmV0"
  ADMIN_JWT_SECRET: "YWRtaW5fYXV0aF9tc19qd3Rfc2VjcmV0"
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="
  DB_NAME: "YWF3LW1hcmtldHBsYWNl"