apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: aaw-backend
data:
  PRODUCT_HOST: products.aaw-backend.svc.cluster.local
  DB_HOST: orders-db.aaw-backend.svc.cluster.local
  DB_PORT: "5433"
  NODE_ENV: production
  PORT: "8002"
  TENANT_ID: e4f770bf-9181-4d75-8ebe-8a9e4db5055c