apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: aaw-backend
  labels:
    app: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: rayhanrandi10/aaw-orders:capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: orders-config
        - secretRef:
            name: orders-secrets
        volumeMounts:
        - name: vector-log-volume
          mountPath: /logs
        resources:
          requests: 
            cpu: "100m"
            memory: "128Mi"

      - name: vector-agent
        image: timberio/vector:0.42.0-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 8686
        envFrom:
        - configMapRef:
            name: authentication-config
        volumeMounts:
        - name: vector-log-volume
          mountPath: /logs
        - name: vector-config-volume
          mountPath: /etc/vector
        args: 
            - "-c"
            - "/etc/vector/vector.yaml"
      volumes:
      - name: vector-log-volume
        emptyDir: {}
      - name: vector-config-volume
        configMap:
          name: orders-config

---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: aaw-backend
  labels:
    app: orders
spec:
  type: NodePort
  selector:
    app: orders
  ports:
  - name: http
    protocol: TCP
    nodePort:  30002
    port: 8002
    targetPort: 8002