apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: aaw-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: orders-orders:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: orders-config
        - secretRef:
            name: orders-secrets
        volumeMounts:
        - name: orders-storage
          mountPath: /app/data
      volumes:
      - name: orders-storage
        persistentVolumeClaim:
          claimName: orders-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: aaw-backend
spec:
  type: NodePort
  selector:
    app: orders
  ports:
  - protocol: TCP
    port:  30002
    targetPort: 8002