apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: products-hpa
  namespace: aaw-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products
  minReplicas: 2
  maxReplicas: 7
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50