apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wishlist-pvc
  namespace: aaw-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""