apiVersion: v1
kind: PersistentVolume
metadata:
  name: products-pv
  namespace: aaw-backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: local-path