apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-pvc
  namespace: aaw-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard