version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - $PROM_PORT:$PROM_PORT
    networks:
      - marketplace-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $GRAFANA_PORT:$GRAFANA_PORT
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    networks:
      - marketplace-net

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - marketplace-net

networks:
  marketplace-net:
    name: marketplace-net
    driver: bridge
  