apiVersion: v1
kind: ConfigMap
metadata:
  name: wishlist-config
  namespace: aaw-backend
data:
  TENANT_ID: e4f770bf-9181-4d75-8ebe-8a9e4db5055c
  DB_HOST: wishlist-db.aaw-backend.svc.cluster.local
  DB_PORT: "5436"
  NODE_ENV: production
  PORT: "8005"
  vector.yaml: |
    sources:
      logfile:
        type: file
        include:
          - ./logs/*.log

    transforms:
      parse_json:
        type: remap
        inputs:
          - logfile
        source: |
          del(.file)
          del(.source_type)
          . = parse_json!(.message)
          .time = now()
          
    sinks:
      loki:
        type: loki
        inputs:
          - parse_json
        compression: snappy
        endpoint: http://loki:3100
        labels:
          container: app-wishlist
          stream: stream-wishlist
          level: "{{ .level }}"
          hostname: "{{ .hostname }}"
          pid: "{{ .pid }}"
        encoding:
          codec: json