{
 "title": "AAW Marketplace",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "CPU Usage - Last 1m (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"marketplace-auth\"}[1m]) * 100",
     "legendFormat": "svc-authentication"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"marketplace-orders\"}[1m]) * 100",
     "legendFormat": "svc-orders"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"marketplace-products\"}[1m]) * 100",
     "legendFormat": "svc-products"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"marketplace-tenant\"}[1m]) * 100",
     "legendFormat": "svc-tenant"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"marketplace-wishlist\"}[1m]) * 100",
     "legendFormat": "svc-wishlist"
    }
   ]
  },
  {
   "title": "Memory Usage - Last 1m (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"marketplace-auth\"} / 1024 / 1024 / 1024",
     "legendFormat": "svc-authentication"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"marketplace-orders\"} / 1024 / 1024 / 1024",
     "legendFormat": "svc-orders"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"marketplace-products\"} / 1024 / 1024 / 1024",
     "legendFormat": "svc-products"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"marketplace-tenant\"} / 1024 / 1024 / 1024",
     "legendFormat": "svc-tenants"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"marketplace-wishlist\"} / 1024 / 1024 / 1024",
     "legendFormat": "svc-wishlist"
    }
   ]
  },
  {
   "title": "Throughput - Last 1m (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_request_duration_seconds_count{job=\"marketplace-auth\"}[1m]))",
     "legendFormat": "svc-authentication"
    },
    {
     "expr": "sum by(job) (rate(http_request_duration_seconds_count{job=\"marketplace-orders\"}[1m]))",
     "legendFormat": "svc-orders"
    },
    {
     "expr": "sum by(job) (rate(http_request_duration_seconds_count{job=\"marketplace-products\"}[1m]))",
     "legendFormat": "svc-products"
    },
    {
     "expr": "sum by(job) (rate(http_request_duration_seconds_count{job=\"marketplace-tenant\"}[1m]))",
     "legendFormat": "svc-tenants"
    },
    {
     "expr": "sum by(job) (rate(http_request_duration_seconds_count{job=\"marketplace-wishlist\"}[1m]))",
     "legendFormat": "svc-wishlist"
    }
   ]
  },
  {
   "title": "Latency - Last 1m (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"marketplace-auth\"}[1m])) by (le)) * 1000",
     "legendFormat": "svc-authentication"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"marketplace-orders\"}[1m])) by (le)) * 1000",
     "legendFormat": "svc-orders"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"marketplace-products\"}[1m])) by (le)) * 1000",
     "legendFormat": "svc-products"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"marketplace-tenant\"}[1m])) by (le)) * 1000",
     "legendFormat": "svc-tenants"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"marketplace-wishlist\"}[1m])) by (le)) * 1000",
     "legendFormat": "svc-wishlist"
    }
   ]
  },
  {
   "title": "Error Rate - Last 1m (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(count(http_request_duration_seconds_count{job=\"marketplace-auth\", status_code=~\"4..|5..\"} offset 1m) / count(http_request_duration_seconds_count{job=\"marketplace-auth\"} offset 1m)) * 100",
     "legendFormat": "svc-authentication"
    },
    {
     "expr": "(count(http_request_duration_seconds_count{job=\"marketplace-orders\", status_code=~\"4..|5..\"} offset 1m) / count(http_request_duration_seconds_count{job=\"marketplace-orders\"} offset 1m)) * 100",
     "legendFormat": "svc-orders"
    },
    {
     "expr": "(count(http_request_duration_seconds_count{job=\"marketplace-products\", status_code=~\"4..|5..\"} offset 1m) / count(http_request_duration_seconds_count{job=\"marketplace-products\"} offset 1m)) * 100",
     "legendFormat": "svc-products"
    },
    {
     "expr": "(count(http_request_duration_seconds_count{job=\"marketplace-tenant\", status_code=~\"4..|5..\"} offset 1m) / count(http_request_duration_seconds_count{job=\"marketplace-tenant\"} offset 1m)) * 100",
     "legendFormat": "svc-tenants"
    },
    {
     "expr": "(count(http_request_duration_seconds_count{job=\"marketplace-wishlist\", status_code=~\"4..|5..\"} offset 1m) / count(http_request_duration_seconds_count{job=\"marketplace-wishlist\"} offset 1m)) * 100",
     "legendFormat": "svc-wishlist"
    }
   ]
  },
  {
   "title": "Memory Usage - Current (GB)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"marketplace-auth\"} / 1024 / 1024 / 1024",
     "legendFormat": "svc-authentication"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"marketplace-orders\"} / 1024 / 1024 / 1024",
     "legendFormat": "svc-orders"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"marketplace-products\"} / 1024 / 1024 / 1024",
     "legendFormat": "svc-products"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"marketplace-tenant\"} / 1024 / 1024 / 1024",
     "legendFormat": "svc-tenants"
    },
    {},
    {
     "expr": "process_resident_memory_bytes{job=\"marketplace-wishlist\"} / 1024 / 1024 / 1024",
     "legendFormat": "svc-wishlist"
    }
   ]
  }
 ]
}