{
 "title": "Logs",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "info" }
  ]
 },
 "panels": [
  {
   "title": "Total Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"app-auth\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(service_name) (count_over_time({service_name=\"$service_name\"} [$__interval]))",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"$service_name\"} |~ `(?i)$searchable_pattern` [$__interval]))"
    }
   ]
  },
  {
   "title": "Log Frequency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "count(rate({service_name=\"$service_name\"} |~ `$searchable_pattern` [$__interval]))",
     "legendFormat": "Frequency"
    },
    {
     "expr": "count(rate({service_name=\"$service_name\"} |~ \"error\" [$__interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{service_name=\"$service_name\"} |~ `$searchable_pattern` | json | label_format status=\"{{.level}}\" | line_format `[hostname {{.hostname}} with PID {{.pid}}] - {{.status}} - {{ .msg }}`"
    }
   ]
  }
 ]
}