apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: aaw-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: authentication-authentication:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: authentication-config
        - secretRef:
            name: authentication-secrets
        volumeMounts:
        - name: authentication-storage
          mountPath: /app/data
      volumes:
      - name: authentication-storage
        persistentVolumeClaim:
          claimName: authentication-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: aaw-test
spec:
  type: NodePort
  selector:
    app: authentication
  ports:
  - protocol: TCP
    nodePort:  30000
    port: 8000
    targetPort: 8000