apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist
  namespace: aaw-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
      - name: wishlist
        image: wishlist-wishlist:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8005
        envFrom:
        - configMapRef:
            name: wishlist-config
        - secretRef:
            name: wishlist-secrets
        volumeMounts:
        - name: wishlist-storage
          mountPath: /app/data
      volumes:
      - name: wishlist-storage
        persistentVolumeClaim:
          claimName: wishlist-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wishlist
  namespace: aaw-test
spec:
  type: NodePort
  selector:
    app: wishlist
  ports:
  - protocol: TCP
    nodePort:  30005
    port:  8005
    targetPort: 8005
    