apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentication-pv
  namespace: aaw-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: local-path