version: '3.8'

services:
  authentication:
    build: .
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    environment:
      - TENANT_ID=${TENANT_ID}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - log_data:/logs/
    depends_on:
      - auth-db
    networks:
      - marketplace-net

  auth-db:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${DB_MIGRATION_PATH}:/docker-entrypoint-initdb.d/1_init.sql
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-net

  auth-vector:
    depends_on:
      - authentication
    image: timberio/vector:0.42.0-alpine
    container_name: auth-vector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      # mount log file paths as necessary with :ro read only permissions
      - log_data:/var/log/data/authentication:ro
    env_file:
      - .env
    ports:  
      - "8686:8686"
    networks:
      - marketplace-net

volumes:
  log_data:
  postgres_data:

networks:
  marketplace-net:
    name: marketplace-net
    driver: bridge