version: '3.8'

services:
  authentication:
    build: .
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    environment:
      - TENANT_ID=${TENANT_ID}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - auth-db
    networks:
      - marketplace-net

  auth-db:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${DB_MIGRATION_PATH}:/docker-entrypoint-initdb.d/1_init.sql
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-net

volumes:
  postgres_data:

networks:
  marketplace-net:
    name: marketplace-net
    driver: bridge